# -*- coding: utf-8 -*-
# Unofficial machine-generated working translations of the Ratio Studiorum
# of 1599, made for this site directly from the Latin of the Institutum
# Societatis Iesu, vol. III (Florence, 1893), consulting no copyrighted
# translation. Dedicated to the public domain under CC0 1.0. They carry no
# authority of any kind — cite the Latin. Imported by build-ratio.py.

EN_THEOL = {
 1: ("Let him understand that it is his office so to join the solid subtlety of "
     "disputation with orthodox faith and piety, that the former serve the latter "
     "above all."),
 2: ("In scholastic theology let Ours follow altogether the doctrine of St. Thomas, "
     "hold him as their own proper Doctor, and put all their effort into it, that "
     "their hearers may be as well affected toward him as possible. Yet they should "
     "not understand themselves to be so bound to St. Thomas that it is never "
     "permitted to depart from him in anything; since those very men who most "
     "profess themselves Thomists sometimes depart from him, and it is not fitting "
     "that Ours be tied to St. Thomas more tightly than the Thomists themselves."),
 3: ("Therefore on the Conception of the Blessed Mary and on the solemnity of vows "
     "let them follow the opinion that is at this time the more common and the more "
     "received among theologians; and in questions purely philosophical, or in those "
     "that pertain to the Scriptures and the Canons, it will be permitted to follow "
     "others also, who have treated those faculties more professedly."),
 4: ("If ever the opinion of St. Thomas is ambiguous, or if, in questions that St. "
     "Thomas perhaps did not touch, Catholic Doctors do not agree among themselves, "
     "it will be permitted to follow either side, as is said in the Common Rules, "
     "rule five."),
 5: ("In teaching, let care be taken first to strengthen faith and to nourish piety. "
     "Therefore in questions that St. Thomas does not treat professedly, let no one "
     "teach anything that does not agree well with the sense of the Church and the "
     "received traditions, or that in any way diminishes the firmness of solid "
     "piety. To this it belongs that they neither refute the received arguments, "
     "however merely fitting, by which the matters of faith are usually proved, nor "
     "rashly devise new ones, except from constant and solid principles."),
 6: ("Opinions which, whoever their author, are known gravely to offend Catholics "
     "in some province or academy, let him not teach or defend there. For where "
     "neither the doctrine of the faith nor the integrity of morals is put at risk, "
     "prudent charity requires that Ours accommodate themselves to those among whom "
     "they live."),
 7: ("The whole course of theology is to be completed in four years. If, then, "
     "there are two professors of scholastic theology: § 1. Let the first explain "
     "forty-three questions of the first part in the first year; in the second "
     "year, the matter on the angels and twenty-one questions of the first part of "
     "the second; in the third year, from question 55 or 71 to the end of the first "
     "part of the second; in the fourth year, from the second part of the second, "
     "the matter on faith, hope and charity. § 2. Let the other professor, in the "
     "first year, expound from the second part of the second the questions on "
     "justice and right and certain principal matters on religion; in the second, "
     "from the third part, the questions on the Incarnation and, if he can, at "
     "least the weightier points on the sacraments in general; in the third, on "
     "baptism and the Eucharist and, what he can, on order, confirmation and "
     "extreme unction; in the fourth, on penance and matrimony. § 3. But where "
     "there are three professors of theology, let the first in the first year set "
     "out twenty-six questions of the first part; in the second, whatever questions "
     "of the same part he can; in the third, whatever he can of the first part of "
     "the second before question 81; in the fourth year, the rest of the first part "
     "of the second. § 4. The second: in the first year, from the second part of "
     "the second, the controversies on Scripture and traditions, on the Church, on "
     "the Council, on the Roman Pontiff; in the second, the questions on faith, "
     "hope and charity; in the third, the questions on justice and right, on "
     "restitution and usury, on contracts, as much as he can; in the fourth, "
     "whatever remained on contracts, and what he disputes on religion and the "
     "states of life. § 5. The third: in the first year, the questions on the "
     "Incarnation; in the second, on the sacraments in general, on baptism and the "
     "Eucharist; in the third, on penance and matrimony; in the fourth, on "
     "ecclesiastical censures and the remaining sacraments."),
 8: ("Of the questions he is to expound, let him finish each within the year to "
     "which it is assigned; those he cannot, let him omit altogether and not put "
     "off to another year, but refer his hearers to some fixed author."),
 9: ("That they may more easily make progress of this kind in scholastic theology, "
     "it is fitting that they abstain, as far as may be, from certain kinds of "
     "matter — chiefly these four: § 1. One kind comprises the questions or "
     "commentaries proper to the divine Scriptures: these let them yield to the "
     "interpreter of Scripture. § 2. A second kind lies in the controversies "
     "against the heretics; in handling these, whenever they occur in the parts of "
     "St. Thomas, let them keep the scholastic rather than the historical method, "
     "and think it enough to fortify each conclusion with two or three firm "
     "foundations, and likewise to dissolve about as many principal calumnies of "
     "the heretics — yet in each case naming some author from whom whoever wishes "
     "may draw the rest. § 3. In the third kind are philosophical matters, which "
     "they should by no means treat professedly, nor so much dispute as indicate "
     "where they have been explained by others or by themselves. § 4. To the "
     "fourth kind belong cases of conscience: here, content with certain general "
     "principles of moral matters that are usually disputed in the theological "
     "manner, let them pass over that subtler and more minute explication of "
     "cases."),
 10: ("If St. Thomas ever draws out the same difficulty into several articles, "
      "especially of different questions, then, lest the same thing be repeated in "
      "two places, they may gather those articles either into one disputation or "
      "even, if the matter does not demand a longer explication, into a summary, "
      "as will be said distinctly in the Catalogue of Questions annexed to these "
      "Rules — provided they pass over nothing in the several articles that is "
      "worthy of observation."),
 11: ("Let them run through the easy articles. Thus, the title having been read, "
      "let them either briefly indicate St. Thomas's conclusion or say: St. Thomas "
      "answers by denying, or by affirming. In the more difficult ones let them "
      "proceed roughly in this way and order: first let the title of the article "
      "be explained, if it has any obscurity; then let the distinction be set out, "
      "if there is one, from whose members the conclusions arise; next let the "
      "primary conclusion of St. Thomas be stated, and then the others; and to "
      "each conclusion, unless it is evident, let some reason of his be added — "
      "and let this too be so explained that the hearers understand that there is "
      "more force in the distinctions and reasons of St. Thomas than sometimes "
      "appears at first sight."),
 12: ("When any article has been explained, let him take up a question if the "
      "matter requires; yet no longer treatise, except in those matters which "
      "either are not found in St. Thomas, or are found indeed but are more "
      "usefully explained in summary."),
 13: ("It is not enough to report the opinions of the Doctors and keep silence "
      "about his own; let him defend the opinion of St. Thomas, as has been said, "
      "or omit the question itself."),
 14: ("In the monthly disputations, at which as many will defend as there are "
      "teachers, let about three argue before noon and as many after noon, each "
      "against all the defenders; and indeed, if nothing prevents, let him who "
      "answered first in the morning answer second after dinner."),
}

EN_PHIL = {
 1: ("Since the arts or natural sciences dispose the mind for theology, and serve "
     "for its perfect knowledge and use, and of themselves help toward the same "
     "end, let the teacher — seeking sincerely in all things the honor and glory "
     "of God — treat them with the diligence that is fitting, so as to prepare "
     "his hearers, and especially Ours, for theology, and above all to stir them "
     "to the knowledge of their Creator."),
 2: ("In matters of any moment let him not depart from Aristotle, unless something "
     "occurs foreign to the doctrine which the academies everywhere approve — much "
     "more if it is repugnant to the orthodox faith: against which, if there are "
     "arguments of his or of any other philosopher, let him strive strenuously to "
     "refute them, according to the Lateran Council."),
 3: ("The interpreters of Aristotle who have deserved ill of the Christian "
     "religion let him not read, or bring into the school, without great "
     "selection; and let him take care that the students are not drawn to them."),
 4: ("For that reason let him not gather the digressions of Averroes (and the "
     "judgment is the same of others of that kind) into some separate treatise; "
     "and if anything good is to be cited from him, let him cite it without "
     "praise, and, if it can be done, show that he took it from elsewhere."),
 5: ("Let him bind neither himself nor his students to any sect, such as the "
     "Averroists, the Alexandrians and the like; and let him not dissemble the "
     "errors of Averroes, of Alexander or of the rest, but use them to press down "
     "their authority the more sharply."),
 6: ("Of St. Thomas, on the contrary, let him never speak but with honor: "
     "following him with willing mind whenever it is proper, or, when he pleases "
     "less, departing from him with reverence and reluctance."),
 7: ("Let him lecture on the whole of philosophy in not less than three years, "
     "and that for two hours daily, one before noon and one after, unless it is "
     "ordered otherwise in some university."),
 8: ("And accordingly let the course nowhere be finished before the vacations "
     "that are usually given toward the end of the year have arrived, or are very "
     "near."),
 9: ("§ 1. In the first year let him explain logic, its summary having been "
     "delivered in about the first two months, not so much by dictating as by "
     "explaining, out of Toletus or Fonseca, what shall seem more necessary. "
     "§ 2. In the prolegomena of logic let him dispute only whether it is a "
     "science, and of what subject, and a few things about second intentions; "
     "the full disputation on universals let him defer to metaphysics, content "
     "here to give a moderate acquaintance with them. § 3. Of the categories too "
     "let him propose certain easier points, which are for the most part touched "
     "by Aristotle, and put off the rest to the last year. Yet of analogy and "
     "relation, since they fall most frequently into disputations, let him treat "
     "in logic as much as is enough. § 4. The second book of the Perihermenias "
     "and both books of the Prior Analytics — beyond the first eight or nine "
     "chapters of the first — let him run through in summary; yet let him set out "
     "their proper questions, and very briefly the one on contingents, in which "
     "nothing on free will. § 5. And, that the second year may be given whole to "
     "physics, at the end of the first year let a fuller disputation on science "
     "be held, and into it let the prolegomena of physics be brought for the "
     "greatest part — the divisions of the sciences, the abstractions, the "
     "speculative and the practical, subalternation, likewise the different "
     "manner of proceeding in physics and in mathematics, of which Aristotle in "
     "book 2 of the Physics, and finally whatever is said of definition in book 2 "
     "On the Soul. § 6. From the Topics and the Refutations, the places and the "
     "fallacies, reduced to a more convenient order, are better explained at the "
     "beginning of logic, in the summary."),
 10: ("§ 1. In the second year let him explain the eight books of the Physics, "
      "the books On the Heavens, and the first On Generation. In the eight books "
      "of the Physics let the text of the sixth and seventh books be delivered in "
      "summary, and of the first too in that part which concerns the opinions of "
      "the ancients. In the eighth book let nothing be discussed of the number of "
      "the intelligences, nor of liberty, nor of the infinity of the first mover; "
      "let these be disputed in metaphysics, and indeed only according to the "
      "opinion of Aristotle. § 2. Let the texts of the second, third and fourth "
      "On the Heavens be touched briefly, and for a great part passed over. In "
      "these books let nothing be treated but a few questions on the elements; "
      "and of the heavens, only of their substance and of the influences: the "
      "rest are to be left to the professor of mathematics, or brought into a "
      "summary. § 3. The Meteorology is to be run through in the summer months "
      "in the last afternoon hour of school, whether by the ordinary professor "
      "of philosophy, if he can, or by an extraordinary one — unless it should "
      "seem more convenient to do otherwise."),
 11: ("§ 1. In the third year he will explain the second book On Generation, the "
      "books On the Soul, and the Metaphysics. In the first book On the Soul let "
      "him run through the opinions of the ancient philosophers summarily. In "
      "the second, the sense-organs having been expounded, let him not digress "
      "into anatomy and the other things that belong to the physicians. § 2. In "
      "metaphysics, the questions on God and the intelligences, which depend "
      "wholly or greatly on truths handed down by divine faith, are to be passed "
      "over. The proem, and the text of the seventh and twelfth books, is for a "
      "great part to be explained diligently; in the other books let certain "
      "principal texts be selected from each, as foundations of the questions "
      "that belong to the metaphysician."),
 12: ("Let him endeavor with all his might to interpret the Aristotelian text "
      "well, and spend no less labor on this than on the questions. Let him also "
      "persuade his hearers that the philosophy of those who hold that study of "
      "no account will be very mutilated and maimed."),
 13: ("Whenever he comes upon texts that are very celebrated and often tossed "
      "about in disputations, let him weigh them accurately, comparing several of "
      "the more distinguished interpretations, so that it may be understood which "
      "is to be preferred to which — from what precedes and follows, or from the "
      "force of the Greek, or from the observation of other passages, or from the "
      "authority of the more notable interpreters, or finally from the weight of "
      "the reasons. Then only let him come to certain small doubts, not indeed to "
      "be pursued too far, but, if they are of any moment, not to be omitted."),
 14: ("Let him also make a great selection of questions: and those which do not "
      "arise from Aristotle's own disputation but on the occasion of some axiom "
      "that he uses in passing while disputing, if they have their proper place "
      "in other books, are to be sent back there; if not, let them be explained "
      "immediately after the very text in which they presented themselves."),
 15: ("But questions that of themselves belong to the matter of which Aristotle "
      "disputes are not to be treated before all the texts pertaining to the "
      "proposed sum of the matter have been explained — provided these texts are "
      "not more than can be set out in one or two lectures. But if they run out "
      "longer, as do those on the principles, on the causes, on motion, then let "
      "neither fuller treatises be held in them, nor the whole context of "
      "Aristotle be set before the questions, but let it be so joined with them "
      "that after some series of texts certain questions arising from them are "
      "interposed."),
 16: ("The lectures ended, let some of them go over together what they have heard "
      "for half an hour, about ten at a time, one of the fellow students from the "
      "Society, if it can be done, being set over each group of ten."),
 17: ("Let monthly disputations be held, at which not fewer than three argue in "
      "the morning and as many after dinner; the first indeed for an hour, the "
      "rest for about three quarters each. And in the morning let some "
      "theologian (if there is a supply of theologians) dispute in the first "
      "place against the metaphysician, the metaphysician against the physicist, "
      "the physicist against the logician; but after dinner metaphysician with "
      "metaphysician, physicist with physicist, logician with logician. Likewise "
      "in the morning the metaphysician, after dinner the physicist, will "
      "briefly and philosophically confirm one or two conclusions."),
 18: ("While the teacher delivers the summary of logic, let neither he nor his "
      "hearers come to these disputations. Indeed for about the first week or "
      "two let the logicians dispute nothing, content almost with the "
      "explanation of the matter; from that time they may defend some theses in "
      "their own class on Saturday."),
 19: ("Where there is but one master of philosophy, let him hold three or four "
      "times a year some more solemn disputations on a feast day or other "
      "holiday, and that with such splendor and apparatus — religious and other "
      "doctors being invited to argue — that from this some not unfruitful "
      "fervor may accrue to our studies."),
 20: ("From the very beginning of logic let the young men be so trained that "
      "nothing shames them more in disputing than to have swerved from the order "
      "of form; and let the teacher exact nothing from them more severely than "
      "the laws and appointed turns of disputing. Therefore let him who answers "
      "first repeat the whole argumentation, answering nothing to the several "
      "propositions; then the propositions again, adding I deny, or I concede, "
      "the major, the minor, the consequence; sometimes let him also "
      "distinguish; but rarely let him obtrude declarations or reasons, "
      "especially on the unwilling."),
}
